name: data_quilt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - codecov
  - pip
  - requests
  - pillow
  - pandas 
  - jupyter
  - ipython
  - pylint
  - pytest
  - pytest-cov
  - geopy
  - pip:
      - matplotlib
      - swatch
    
variables:
  TOKEN: ***REMOVED***

