name: dataquilt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - setuptools
  - codecov
  - pip
  - requests
  - pillow
  - pandas
  - jupyter
  - ipython
  - pylint
  - pytest>=6.0
  - pytest-cov
  - geopy
  - pre-commit
  - pip:
      - matplotlib
      - swatch
    
variables:
  TOKEN: ***REMOVED***

