name: Test

on:
  [push, pull_request, workflow_dispatch]

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
     # - uses: actions/checkout@v3
     # - uses: conda-incubator/setup-miniconda@v3
     #   uses: actions/setup-python@v3
      - name: Checkout
        uses: actions/checkout@v2.5.0


      - name: Setup Miniconda
        - uses: conda-incubator/setup-miniconda@v2.2.0

    - name: Install dependencies

        with:
          activate-environment: dataquilt
          environment-file: environment.yml
          auto-activate-base: false

      - name: Activate conda environment
        run: |
          conda info
          conda list
          conda activate dataquilt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest -vv
