name: Python Package using Conda

on: [push, pull_request]

jobs:
  default-shell:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        architecture: "x64"
    - name: setup-conda
      uses: s-weigand/setup-conda@v1
    - run: conda --version
    - run: which python
    - run: conda update conda
    - run: conda env list
    - run: conda env update --file env.yml --name base 
    - run: source activate base

    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pytest
